export enum TagColor {
  GRAY = "gray",
  RED = "red",
  ORANGE = "orange",
  AMBER = "amber",
  YELLOW = "yellow",
  LIME = "lime",
  GREEN = "green",
  EMERALD = "emerald",
  TEAL = "teal",
  CYAN = "cyan",
  SKY = "sky",
  BLUE = "blue",
  INDIGO = "indigo",
  VIOLET = "violet",
  PURPLE = "purple",
  FUCHSIA = "fuchsia",
  PINK = "pink",
  ROSE = "rose",
}

export const tagColors: ReadonlyArray<TagColor> = [
  TagColor.GRAY,
  TagColor.RED,
  TagColor.ORANGE,
  TagColor.AMBER,
  TagColor.YELLOW,
  TagColor.LIME,
  TagColor.GREEN,
  TagColor.EMERALD,
  TagColor.TEAL,
  TagColor.CYAN,
  TagColor.SKY,
  TagColor.BLUE,
  TagColor.INDIGO,
  TagColor.VIOLET,
  TagColor.PURPLE,
  TagColor.FUCHSIA,
  TagColor.PINK,
  TagColor.ROSE,
] as const;
